// Label & kelas warna untuk semua status (client, sesi, invoice, layanan). Dipakai lewat <StatusBadge/>.

export const STATUS_META = {
  inquiry: { label: "Inquiry Baru", cls: "bg-sky-50 text-sky-700 border border-sky-200/70" },
  service_selected: { label: "Layanan Dipilih", cls: "bg-purple-50 text-purple-700 border border-purple-200/70" },
  assessment_scheduled: { label: "Asesmen Terjadwal", cls: "bg-blue-50 text-blue-700 border border-blue-200/70" },
  assessment_done: { label: "Asesmen Selesai", cls: "bg-teal-50 text-teal-700 border border-teal-200/70" },
  admitted: { label: "Active Client", cls: "bg-emerald-50 text-emerald-700 border border-emerald-200/70" },
  active: { label: "Active Client", cls: "bg-emerald-50 text-emerald-700 border border-emerald-200/70" },
  done_consult: { label: "Done Consult", cls: "bg-amber-50 text-amber-800 border border-amber-200/70" },
  done_assessment: { label: "Done Assessment", cls: "bg-indigo-50 text-indigo-700 border border-indigo-200/70" },
  discontinued: { label: "Discontinued", cls: "bg-rose-50 text-rose-700 border border-rose-200/70" },
  discharged: { label: "Discharged", cls: "bg-slate-100 text-slate-700 border border-slate-200/80" },
  scheduled: { label: "Scheduled", cls: "bg-sky-50 text-sky-700 border border-sky-200/70" },
  completed: { label: "Completed", cls: "bg-emerald-50 text-emerald-700 border border-emerald-200/70" },
  cancelled: { label: "Cancelled", cls: "bg-rose-50 text-rose-700 border border-rose-200/70" },
  off: { label: "Off", cls: "bg-violet-50 text-violet-700 border border-violet-200/70" },
  rescheduled: { label: "Rescheduled (Sudah Pindah)", cls: "bg-amber-50 text-amber-700 border border-amber-200/70" },
  reschedule_pending: { label: "Reschedule – Belum Ada Jadwal", cls: "bg-orange-50 text-orange-800 border border-dashed border-orange-300" },
  unpaid: { label: "Belum Lunas", cls: "bg-rose-50 text-rose-700 border border-rose-200/70" },
  paid: { label: "Lunas Terverifikasi", cls: "bg-emerald-50 text-emerald-700 border border-emerald-200/70" },
  void: { label: "Void", cls: "bg-slate-100 text-slate-600 border border-slate-300 line-through decoration-slate-400" },
  frozen: { label: "Frozen (0 Kredit)", cls: "bg-cyan-50 text-cyan-900 border border-cyan-400 font-bold ring-1 ring-cyan-400/40" },
  b_ota: { label: "BOT-A", cls: "bg-indigo-50 text-indigo-700 border border-indigo-200/70" },
  f_ota: { label: "FOT-A", cls: "bg-purple-50 text-purple-700 border border-purple-200/70" },
  bot_a: { label: "BOT-A", cls: "bg-indigo-50 text-indigo-700 border border-indigo-200/70" },
  fot_a: { label: "FOT-A", cls: "bg-purple-50 text-purple-700 border border-purple-200/70" },
  consult_wo_report: { label: "Consultation without Report", cls: "bg-cyan-50 text-cyan-700 border border-cyan-200/70" },
  consult_w_report: { label: "Consultation with written report", cls: "bg-teal-50 text-teal-700 border border-teal-200/70" },
  assessment: { label: "Asesmen Klinis", cls: "bg-indigo-50 text-indigo-700 border border-indigo-200/70" },
  therapy: { label: "Regular Therapist", cls: "bg-sky-50 text-sky-700 border border-sky-200/70" },
  therapy_vip: { label: "Senior Therapist", cls: "bg-purple-50 text-purple-700 border border-purple-200/70" },
  therapy_speech: { label: "Terapi Wicara", cls: "bg-teal-50 text-teal-700 border border-teal-200/70" },
  therapy_physio: { label: "Fisioterapi", cls: "bg-orange-50 text-orange-700 border border-orange-200/70" },
};
